# config/settings.yml
group_colors_enabled:
  default: true
  client: true
  description: "Enable group colors plugin"

group_colors_hover_delay:
  default: 200
  client: true
  description: "Delay in milliseconds before showing user card on hover"

group_colors_show_ranks:
  default: true
  client: true
  description: "Show group ranks in user cards"