# config/settings.yml

plugins:
  group_colors_enabled:
    default: true
    client: true
  group_colors_hover_enabled:
    default: true
    client: true
  group_colors_priority_enabled:
    default: true
    client: true
  group_colors_and_ranks:
    type: enum
    default: ""
    client: true
    choices: "available_groups"
    list: true