# config/settings.yml

group_colors_enabled:
  default: true
  client: true
  type: bool
  description: "Enable group colors plugin"

group_colors_hover_enabled:
  default: true
  client: true
  type: bool
  description: "Enable hover cards for colored usernames"

group_colors_priority_enabled:
  default: true
  client: true
  type: bool
  description: "Enable priority system for group colors"