# config/settings.yml

plugins:
  group_colors_enabled:
    default: true
    client: true
    type: bool
  group_colors_hover_enabled:
    default: true
    client: true
    type: bool
  group_colors_priority_enabled:
    default: true
    client: true
    type: bool
  group_colors_ranks_and_colors:
    type: composite
    default: ''
    client: true
    refresh: true
    preloaded_keys: groups