# config/settings.yml

plugins:
  group_colors_enabled:
    type: bool
    default: true
    client: true
  group_colors_hover_enabled:
    type: bool
    default: true
    client: true
  group_colors_priority_enabled:
    type: bool
    default: true
    client: true
  group_colors_and_ranks:
    type: group_colors_list
    default: ''
    client: true