# config/settings.yml

plugins:
  group_colors_enabled:
    client: true
    default: true
    type: bool
    refresh: true
  group_colors_hover_delay:
    client: true
    default: 200
    type: integer
    refresh: true
  group_colors_show_ranks:
    client: true
    default: true
    type: bool
    refresh: true