# config/settings.yml

group_colors_enabled:
  type: bool
  default: true
  client: true
group_colors_hover_enabled:
  type: bool
  default: true
  client: true
group_colors_priority_enabled:
  type: bool
  default: true
  client: true
group_colors_list:
  type: list
  default: ''
  client: true
  refresh: true